PetVet/PetVet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('petvet/', include('core.urls')),
    path('users/', include('users.urls')),
]

PetVet/core/urls.py
from django.urls import path
from .views import IndexView, MedicalCareList, PetList, TutorList,  VetList, GeneralClinicList, PhysicalExamList, GeneralDhermExamList, PetAllCareList
from .views import MedicalCareDetail, PetDetail, TutorDetail, GeneralClinicDetail, PhysicalExamDetail, GeneralDhermExamDetail
from .views import MedicalCareCreate, PetCreate, TutorCreate, VetCreate, GeneralClinicCreate, PhysicalExamCreate, GeneralDhermExamCreate
from .views import MedicalCareUpdate, PetUpdate, TutorUpdate, VetUpdate, GeneralClinicUpdate, PhysicalExamUpdate, GeneralDhermExamUpdate
from .views import MedicalCareDelete, PetDelete, TutorDelete, VetDelete, GeneralClinicDelete, PhysicalExamDelete, GeneralDhermExamDelete


urlpatterns = [
    path('', IndexView.as_view(), name='index'),


    path('medical_cares/', MedicalCareList.as_view(), name='medical_cares'),
    path('medical_care/<int:pk>', MedicalCareDetail.as_view(),
         name='medical_care_detail'),
    path('medical_care_new/', MedicalCareCreate.as_view(), name='medical_care_new'),
    path('medical_care_edit/<int:pk>',
         MedicalCareUpdate.as_view(), name='medical_care_edit'),
    path('medical_care_delete/<int:pk>',
         MedicalCareDelete.as_view(), name='medical_care_delete'),

    path('pet_all_care_list/<int:pk>', PetAllCareList.as_view(), name='pet_all_care_list'),

    path('pets/', PetList.as_view(), name='pets'),
    path('pet/<int:pk>', PetDetail.as_view(), name='pet_detail'),
    path('pet_new/', PetCreate.as_view(), name='pet_new'),
    path('pet_edit/<int:pk>', PetUpdate.as_view(), name='pet_edit'),
    path('pet_delete/<int:pk>', PetDelete.as_view(), name='pet_delete'),


    path('tutors/', TutorList.as_view(), name='tutors'),
    path('tutor/<int:pk>', TutorDetail.as_view(), name='tutor_detail'),
    path('tutor_new/', TutorCreate.as_view(), name='tutor_new'),
    path('tutor_edit/<int:pk>', TutorUpdate.as_view(), name='tutor_edit'),
    path('tutor_delete/<int:pk>', TutorDelete.as_view(), name='tutor_delete'),


    path('vets/', VetList.as_view(), name='vets'),
    path('vet_new/', VetCreate.as_view(), name='vet_new'),
    path('vet_edit/<int:pk>', VetUpdate.as_view(), name='vet_edit'),
    path('vet_delete/<int:pk>', VetDelete.as_view(), name='vet_delete'),


    path('general_clinics/', GeneralClinicList.as_view(), name='general_clinics'),
    path('general_clinic/<int:pk>', GeneralClinicDetail.as_view(),
         name='general_clinic_detail'),
    path('general_clinic_new/', GeneralClinicCreate.as_view(),
         name='general_clinic_new'),
    path('general_clinic_edit/<int:pk>',
         GeneralClinicUpdate.as_view(), name='general_clinic_edit'),
    path('general_clinic_delete/<int:pk>',
         GeneralClinicDelete.as_view(), name='general_clinic_delete'),


    path('physical_exams/', PhysicalExamList.as_view(), name='physical_exams'),
    path('physical_exam/<int:pk>', PhysicalExamDetail.as_view(),
         name='physical_exam_detail'),
    path('physical_exam_new/', PhysicalExamCreate.as_view(),
         name='physical_exam_new'),
    path('physical_exam_edit/<int:pk>',
         PhysicalExamUpdate.as_view(), name='physical_exam_edit'),
    path('physical_exam_delete/<int:pk>',
         PhysicalExamDelete.as_view(), name='physical_exam_delete'),


    path('general_dherm_exams/', GeneralDhermExamList.as_view(), name='general_dherm_exams'),
    path('general_dherm_exam/<int:pk>', GeneralDhermExamDetail.as_view(),
         name='general_dherm_exam_detail'),
    path('general_dherm_exam_new/', GeneralDhermExamCreate.as_view(),
         name='general_dherm_exam_new'),
    path('general_dherm_exam_edit/<int:pk>',
         GeneralDhermExamUpdate.as_view(), name='general_dherm_exam_edit'),
    path('general_dherm_exam_delete/<int:pk>',
         GeneralDhermExamDelete.as_view(), name='general_dherm_exam_delete'),
]

PetVet/core/models.py
from django.db import models
from django.urls import reverse
from datetime import date


castrated_status = (('Não', 'Não'), ('Sim', 'Sim'))

sex_status = (('Macho', 'Macho'), ('Fêmea', 'Fêmea'))

procedures = (('Consulta', 'Consulta'), ('Retorno', 'Retorno'),
              ('Exame', 'Exame'), ('Cirurgia', 'Cirurgia'))

type_sedative = (('Não', 'Não'), ('Simples', 'Simples'),
                 ('Complexo', 'Complexo'))

type_anamnese = (('Aula', 'Aula'), ('Rotina', 'Rotina'))

vaccination = (('Não Vacinado', 'Não Vacinado'), ('Não sabe', 'Não Sabe'), ('Vacinado, Desatualizada',
               'Vacinado, Desatualizada'), ('Vacinado, Atualizada', 'Vacinado, Atualizada'))

type_v = (('Nenhuma', 'Nenhuma'), ('V8', 'V8'), ('V10', 'V10'), ('V12', 'V12'))

type_felina = (('Nenhuma', 'Nenhuma'), ('Tríplice', 'Tríplice'),
               ('Quadrúpla', 'Quadrúpla'))

vermi_ecto = (('Não', 'Não'), ('Não sabe Informar', 'Não Sabe Informar'),
              ('Desatualizada', 'Desatualizada'), ('Atualizada', 'Atualizada'))

leish = (('Não', 'Não'), ('Vacinado', 'Vacinado'),
         ('Usa Coleira', 'Usa    Coleira'), ('Atualizada', 'Atualizada'), ('Desatualizada', 'Desatualizada'))

conduct = (('Dócil', 'Dócil'), ('Inquieto', 'Inquieto'), ('Medroso', 'Medroso'),
           ('Agressivo', 'Agressivo'))

consciousness = (('Coma', 'Coma'), ('Estupor', 'Estupor'), ('Confusão', 'Confusão'), ('Normal/Alerta',
                 'Normal/Alerta'), ('Sonolência/Apático', 'Sonolência/Apático'), ('Excitado', 'Excitado'))

nutricional_status = (('Caquético', 'Caquético'), ('Magro', 'Magro'),
                      ('Normal', 'Normal'), ('Gordo', 'Gordo'), ('Obeso', 'Obeso'))

dental_calculus = (('Não', 'Não'), ('Leve', 'Leve'),
                   ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Não Permitiu', 'Não Permitiu'))

dental_loss = (('Não', 'Não'), ('Sim', 'Sim'),
               ('Persistência de dente decíduo', 'Persistência de dente decíduo'), ('Não Permitiu', 'Não Permitiu'))

ulcera = (('Não', 'Não'), ('Sim', 'Sim'), ('Não Permitiu', 'Não Permitiu'))

auscu_cardio = (('Não Permitiu/Não Realizado', 'Não Permitiu/Não Realizado'), ('Bulhas Normofonéticas',
                'Bulhas Normofonéticas'), ('Bulhas Hipofonéticas', 'Bulhas Hipofonéticas'), ('Sopro em Valva', 'Sopro em Valva'))

auscu_pulmonar = (('Ruído Normal', 'Ruído Normal'), ('Alterado', 'Alterado'),
                  ('Não Permitiu', 'Não Permitiu'), ('Não Realizado ACP', 'Não Realizado ACP'))

percu_pulmonar = (('Normal', 'Normal'),
                  ('Submaciço', 'Submaciço'), ('Maciço', 'Maciço'), ('Não Realizado', 'Não Realizado'))

mamas = (('Normal', 'Normal'), ('Secreção', 'Secreção'),
         ('Hiperplasia', 'Hiperplasia'))

nodulo = (('Não', 'Não'), ('Firmes', 'Firmes'), ('Flutuante', 'Flutuante'),
          ('Aderido', 'Aderido'), ('Não Aderido', 'Não Aderido'))

local_pain = (('Não', 'Não'), ('Lado Esquerdo', 'Lado Esquerdo'),
              ('Lado Direito', 'Lado Direito'))

pain_m = (('Não', 'Não'), ('M1', 'M1'), ('M2', 'M2'),
          ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'))

parasitas = (('Não', 'Não'), ('Carrapato', 'Carrapato'),
             ('Pulga', 'Pulga'), ('Miíase', 'Miíase'))

classifier = (('Caso Simples', 'Caso Simples'),
              ('Caso Complexo', 'Caso Complexo'))

evolucion_status = (('Piorou', 'Piorou'), ('Melhorou', 'Melhorou'),
                    ('Não evoluiu', 'Não evoluiu'), ('Não sabe', 'Não sabe'))

score = (('-', '-'), ('0', '0'), ('1', '1'), ('2', '2'),
         ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'),
         ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'))

choice_prurido = (('-', '-'), ('Esporádico', 'Esporádico'),
                  ('Frequente', 'Frequente'), ('Sazonal', 'Sazonal'),
                  ('Não sazonal', 'Não sazonal'), ('Diurno', 'Diurno'),
                  ('Noturno', 'Noturno'), ('Nos dois períodos', 'Nos dois períodos'))

contacts_sint = (('Sim', 'Sim'), ('Não', 'Não'),
                 ('Não sei', 'Não sei'), ('do paciente em atendimento foi antes', 'do paciente em atendimento foi antes'), ('do contactante foi antes', 'do contactante foi antes'))

contacts_access = (('Sim', 'Sim'), ('Não', 'Não'),
                   ('Esporadicamente', 'Esporadicamente'), ('Frequentemente', 'Frequentemente'), ('Diariamente', 'Diariamente'))

contacts_sleep = (('Fora de casa', 'Fora de casa'),
                  ('Dentro de casa', 'Dentro de casa'), ('Os dois', 'Os dois'))

pulgas_carrapatos = (('Não', 'Não'), ('Não sei', 'Não sei'), ('Sim', 'Sim'),
                     ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'))


class Tutor(models.Model):
    """Model representing a classe Tutor."""
    tutor_name = models.CharField(
        max_length=50, verbose_name='Nome do Tutor')
    cpf = models.CharField(max_length=14, null=True,
                           verbose_name='CPF')
    phone = models.CharField(max_length=15, null=True,
                             verbose_name='Telefone')
    email = models.EmailField(max_length=254, verbose_name='Email')
    cep = models.CharField(max_length=9, verbose_name='Cep')
    street = models.CharField(max_length=40, verbose_name='Rua')
    number = models.IntegerField(verbose_name='Numero')
    district = models.CharField(max_length=40, verbose_name='Bairro')
    city = models.CharField(
        max_length=40, default='Petrolina', verbose_name='Cidade')
    state = models.CharField(
        max_length=40, default='Pernambuco', verbose_name='Estado')

    class Meta:
        ordering = ['tutor_name']

    def get_absolute_url(self):
        """Returns the url to access a particular pet instance."""
        return reverse('tutor-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.tutor_name


class Pets(models.Model):
    """Model representing a classe pet."""
    id = models.AutoField(primary_key=True)
    pet_name = models.CharField(
        max_length=30, verbose_name='Nome do Pet')
    species = models.CharField(
        max_length=20, verbose_name='Espécie')
    breed = models.CharField(
        max_length=30, default='SPRD',verbose_name='Raça')
    gender = models.CharField(
        max_length=5, choices=sex_status, verbose_name='Gênero')
    date_of_birth = models.DateField(
        null=True, blank=True, verbose_name='Data de Nascimento')
    castrated = models.CharField(
        max_length=3, choices=castrated_status, default='N', verbose_name='Castrado?')
    weight = models.DecimalField(
        max_digits=6, decimal_places=3, verbose_name='Peso', default=0)
    tutor_name = models.ForeignKey(
        'Tutor', on_delete=models.PROTECT, null=True, verbose_name='Nome do Tutor')

    class Meta:
        ordering = ['-id']

    def get_absolute_url(self):
        """Returns the url to access a particular pet instance."""
        return reverse('pet-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.pet_name


class Vet(models.Model):
    """Model representing a classe Vet."""
    vet_name = models.CharField(
        max_length=30, verbose_name='Nome')

    class Meta:
        ordering = ['vet_name']

    def __str__(self):
        """String for representing the Model object."""
        return self.vet_name


class MedicalCare(models.Model):
    """Model representing a classe Medical care."""
    id = models.AutoField(primary_key=True)
    date = models.DateField(default=date.today, verbose_name='Data')
    time = models.TimeField(verbose_name='Hora')
    pet_name = models.ForeignKey(
        'Pets', on_delete=models.PROTECT, null=True, verbose_name='Nome do Pet')
    procedure = models.CharField(
        max_length=8, choices=procedures, verbose_name='Tipo de atendimento')
    vet_name = models.ForeignKey(
        'Vet', on_delete=models.PROTECT, null=True, verbose_name='Veterinario')
    sedative = models.CharField(
        max_length=8, choices=type_sedative, default='Não', verbose_name='Tipo de sedativo')
    report = models.TextField(
        max_length=1000, verbose_name='Relato do problema')

    class Meta:
        ordering = ['-date']

    def get_absolute_url(self):
        """Returns the url to access a particular medical care instance."""
        return reverse('medical_care_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.procedure} - {self.pet_name} - {self.date}'


class GeneralClinic(models.Model):
    medical_care = models.ForeignKey(
        'MedicalCare', on_delete=models.PROTECT, null=True, verbose_name='Atendimento')
    choice_anamnese = models.CharField(
        max_length=6, choices=type_anamnese, verbose_name='Tipo atendimento')
    anamnese = models.TextField(max_length=2000, verbose_name='Anamnese')
    choice_anti_rabica = models.CharField(
        max_length=23, choices=vaccination, verbose_name='Anti-Rábica')
    choice_type_v = models.CharField(
        max_length=7, choices=type_v, verbose_name='V8/V10/V12')
    choice_v = models.CharField(
        max_length=23, choices=vaccination, verbose_name='Opções V')
    choice_type_felina = models.CharField(
        max_length=23, choices=type_felina, verbose_name='Tríplice/Quádrupla Felina')
    choice_felina = models.CharField(
        max_length=23, choices=vaccination, verbose_name='Opções Felina')
    others_felina = models.CharField(
        max_length=30, null=True, blank=True, verbose_name='Outras Vacinas')
    choice_verminose = models.CharField(
        max_length=17, choices=vermi_ecto, verbose_name='Controle Verminose')
    others_verminose = models.CharField(
        max_length=30, null=True, blank=True, verbose_name='Verminose - Fármaco/Dose/Frequência')
    choice_ectopas = models.CharField(
        max_length=17, choices=vermi_ecto, verbose_name='Prevenção Ectoparasitas')
    others_ectopas = models.CharField(

PetVet/core/templates/core/base_model.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br" class="h-100">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  {% block title %}
  <title>PetVet</title>
  {% endblock %}

  <!-- Favicon icon -->
  <link href="{% static 'img/faviconII.ico/' %}" rel="shortcut icon" type="image/x-icon" />

  <!-- bootstrap -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css/' %}" />

  <!-- Awesome Fonts -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

  <!-- css additional -->
  <link rel="stylesheet" href="{% static 'css/styles.css/' %}" />

  <!--datatables import-->
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.css" />


</head>

<body class="d-flex flex-column h-100">
  <main class="flex-shrink-0  ">

    {% block menu %}
    
    <nav class="navbar navbar-expand-lg sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static 'img/favicon.ico/' %}" height="40" alt="" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <div class="collapse navbar-collapse" id="navbarsExample06">
          <ul class="navbar-nav me-auto mb-2 mb-xl-0">
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'index' %}">
                <i class="fa fa-home" aria-hidden="true"></i>
                Início
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" href="{% url 'medical_cares' %}">
                <i class="fas fa-ambulance" aria-hidden="true"></i>
                Atendimentos
              </a>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link text-dark dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-clipboard-check" aria-hidden="true"></i>
                Cadastros
              </a>
              <ul class="dropdown-menu bg-dark p-2">
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'pets' %}">
                    <i class="fas fa-cat" aria-hidden="true"></i>
                    Pets
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'tutors' %}">
                    <i class="fas fa-child" aria-hidden="true"></i>
                    Tutores
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'vets' %}">
                    <i class="fas fa-user-md" aria-hidden="true"></i>
                    Veterinários
                  </a>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link text-dark dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-heartbeat" aria-hidden="true"></i>
                Exames
              </a>
              <ul class="dropdown-menu bg-dark p-2">
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'general_clinics' %}">
                    <i class="fas fa-briefcase-medical" aria-hidden="true"></i>
                    Clínico
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'physical_exams' %}">
                    <i class="fas fa-crutch" aria-hidden="true"></i>
                    Físico
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="{% url 'general_dherm_exams' %}">
                    <i class="fas fa-allergies" aria-hidden="true"></i>
                    Dermatológico
                  </a>
                </li>
              </ul>
            </li>
          </ul>
          
          <div class="collapse navbar-collapse d-lg-flex justify-content-end">
            <ul class="navbar-nav bd-navbar-nav flex=row">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link text-dark" href="{% url 'meus_dados' %}">
                    <i class="fas fa-user-circle" aria-hidden="true"></i>
                    <span id="username">{{ request.user }}</span>
                  </a>
                 
              </li>

              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'logout' %}">
                  <i class="fas fa-power-off" aria-hidden="true"></i>
                  Sair
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'registrar' %}">
                  <i class="fa fa-user-plus" aria-hidden="true"></i>
                  Registrar
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'login' %}">
                  <i class="fas fa-arrow-alt-circle-right" aria-hidden="true"></i>
                  Login
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
         </div>
        
      </div>
    </nav>
   
    {% endblock %}

    <div class="container py-5">
      {% block content %}
      {% endblock %}
    </div>
      
  </main>

{% block footer %}
<footer class="blog-footer">
  <p>
    <a href="#"><img src="{% static 'img/cat_yellow.png/' %}" width="80" height="80" alt=""></a>
    <h3>PetVet</h3>
  </p>
  <p>Dev: Joey Resende
    <a href="https://www.linkedin.com/in/givanildo-resende/" target="_blank">
      <i class="fab fa-linkedin fa-lg text-black" aria-hidden="true"></i>
    </a>
    <a href="https://github.com/Joey-Resende" target="_blank">
      <i class="fab fa-github fa-lg text-black" aria-hidden="true"></i>
    </a>
  </p>
</footer>
</div>
{% endblock %}
  

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
  <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js/' %}"></script>

  <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.5/datatables.min.js"></script>

  <!--block for scripts-->
  {% block scripts %}


  {% endblock %}

  <!--Js additional-->
  <script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

PetVet/core/templates/core/form_general_clinic.html
{% extends 'core/base_model.html' %} 
{% load crispy_forms_tags %} 
{% load static%} 

{% block title %}
<title>{{ title_window }}</title>
{% endblock %} 

{% block content %}
<div class="col-md-10 mx-auto">
    <h3><strong>{{ title_page }}</strong></h3>
    <p>{{ tips }}</p>
    <hr />
    <br />
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mb-0">
          {{ form.medical_care|as_crispy_field }}
        </div>
        <div class="col-md-6 mb-0">
          {{ form.choice_anamnese|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col mb-0">
          {{ form.anamnese|as_crispy_field }}
        </div>
      </div>
      <div class="row">  
        <div class="col-md-4 mb-0">
          {{ form.choice_anti_rabica|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
          {{ form.choice_type_v|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
            {{ form.choice_v|as_crispy_field }}
        </div>
      </div>
      <div class="row">  
        <div class="col-md-4 mb-0">
          {{ form.choice_type_felina|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
          {{ form.choice_felina|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
            {{ form.others_felina|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-0">
          {{ form.choice_verminose|as_crispy_field }}
        </div>
        <div class="col-md-6 mb-0">
          {{ form.others_verminose|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-0">
          {{ form.choice_ectopas|as_crispy_field }}
        </div>
        <div class="col-md-6 mb-0">
          {{ form.choice_leish|as_crispy_field }}
        </div>
      </div>
      <button type="submit" class="btn btn-warning mt-3">Salvar</button>
    </form>
</div>
{% endblock %} 


{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){

      $("#id_date").mask("00/00/0000");
      $("#id_date_of_birth").mask("00/00/0000");
      $("#id_time").mask("00:00");
      $("#id_cpf").mask("000.000.000-00");
      $("#id_cep").mask("00000-000");
      var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
          }
      };
      
      $('#id_phone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}

PetVet/core/templates/core/form_tutor.html
{% extends 'core/base_model.html' %} 
{% load crispy_forms_tags %} 
{% load static%} 

{% block title %}
<title>{{ title_window }}</title>
{% endblock %} 

{% block content %}
<div class="col-md-10 mx-auto">
    <h3><strong>{{ title_page }}</strong></h3>
    <p>{{ tips }}</p>
    <hr />
    <br />
    <form method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mb-0">
          {{ form.tutor_name|as_crispy_field }}
        </div>
        <div class="col-md-6 mb-0">
          {{ form.cpf|as_crispy_field }}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-0">
          {{ form.phone|as_crispy_field }}
        </div>
        <div class="col-md-6 mb-0">
          {{ form.email|as_crispy_field }}
        </div>
      </div>
      <div class="row">  
        <div class="col-md-4 mb-0">
          {{ form.cep|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
          {{ form.street|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
            {{ form.number|as_crispy_field }}
        </div>
      </div>
      <div class="row">  
        <div class="col-md-4 mb-0">
          {{ form.district|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
          {{ form.city|as_crispy_field }}
        </div>
        <div class="col-md-4 mb-0">
            {{ form.state|as_crispy_field }}
        </div>
      </div>
      <button type="submit" class="btn btn-warning mt-3">Salvar</button>
    </form>
</div>
{% endblock %} 


{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){

      $("#id_date").mask("00/00/0000");
      $("#id_date_of_birth").mask("00/00/0000");
      $("#id_time").mask("00:00");
      $("#id_cpf").mask("000.000.000-00");
      $("#id_cep").mask("00000-000");
      var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
      },
      spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
          }
      };
      
      $('#id_phone').mask(SPMaskBehavior, spOptions);

    });
</script>
{% endblock %}